// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtVlSGTO_ytk16gXQbAVa4c1COtvtOhc',
    appId: '1:849315931892:web:4b8b5ffea829d09ff220a1',
    messagingSenderId: '849315931892',
    projectId: 'tarefasdiarias-ed6b3',
    authDomain: 'tarefasdiarias-ed6b3.firebaseapp.com',
    storageBucket: 'tarefasdiarias-ed6b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPXwlzzzElBBu8-0OwU8VRQlZqiuG_aA0',
    appId: '1:849315931892:android:4befbe3a1adcd158f220a1',
    messagingSenderId: '849315931892',
    projectId: 'tarefasdiarias-ed6b3',
    storageBucket: 'tarefasdiarias-ed6b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHz3LtjTU6ViBYRQ7iaUNHUE0r9G6naXQ',
    appId: '1:849315931892:ios:5d74b7c344956251f220a1',
    messagingSenderId: '849315931892',
    projectId: 'tarefasdiarias-ed6b3',
    storageBucket: 'tarefasdiarias-ed6b3.appspot.com',
    iosClientId: '849315931892-ppe5q2gtnupr9u7pf42jjcc39a4ce0mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHz3LtjTU6ViBYRQ7iaUNHUE0r9G6naXQ',
    appId: '1:849315931892:ios:cb79744ea77b4a6bf220a1',
    messagingSenderId: '849315931892',
    projectId: 'tarefasdiarias-ed6b3',
    storageBucket: 'tarefasdiarias-ed6b3.appspot.com',
    iosClientId: '849315931892-8p4eqvabslm5du2a457bccv12e78gduv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarefas.RunnerTests',
  );
}
